//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotroSignatures {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LotroSignatures.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2008 by Felarion (DE-Morthond).
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armourer.
        /// </summary>
        internal static string armourer {
            get {
                return ResourceManager.GetString("armourer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armsman.
        /// </summary>
        internal static string armsman {
            get {
                return ResourceManager.GetString("armsman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burglar.
        /// </summary>
        internal static string burglar {
            get {
                return ResourceManager.GetString("burglar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain.
        /// </summary>
        internal static string captain {
            get {
                return ResourceManager.GetString("captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champion.
        /// </summary>
        internal static string champion {
            get {
                return ResourceManager.GetString("champion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose race, class
        ///and level.
        /// </summary>
        internal static string chooseRaceClass {
            get {
                return ResourceManager.GetString("chooseRaceClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string class_ {
            get {
                return ResourceManager.GetString("class_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cook.
        /// </summary>
        internal static string cook {
            get {
                return ResourceManager.GetString("cook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Clipboard.
        /// </summary>
        internal static string copy2clipboard {
            get {
                return ResourceManager.GetString("copy2clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put in your
        ///crafting progress.
        /// </summary>
        internal static string craftingProgress {
            get {
                return ResourceManager.GetString("craftingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am doing freep-side PvMP.
        /// </summary>
        internal static string doingPvp {
            get {
                return ResourceManager.GetString("doingPvp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwarf.
        /// </summary>
        internal static string dwarf {
            get {
                return ResourceManager.GetString("dwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elf.
        /// </summary>
        internal static string elf {
            get {
                return ResourceManager.GetString("elf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name
        ///and server.
        /// </summary>
        internal static string enterNameServer {
            get {
                return ResourceManager.GetString("enterNameServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer.
        /// </summary>
        internal static string explorer {
            get {
                return ResourceManager.GetString("explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting Image Data....
        /// </summary>
        internal static string extractingImageData {
            get {
                return ResourceManager.GetString("extractingImageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmer.
        /// </summary>
        internal static string farmer {
            get {
                return ResourceManager.GetString("farmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you like it? Consider sending some gold to Felarion on [DE] Morthond ;)
        ///
        ///Additional credits go to:
        /// - lotro-wiki.com from where I took some of the used images
        /// - Turbine for the signature templates (and for the great game).
        /// </summary>
        internal static string finalText {
            get {
                return ResourceManager.GetString("finalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string finished {
            get {
                return ResourceManager.GetString("finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forester.
        /// </summary>
        internal static string forester {
            get {
                return ResourceManager.GetString("forester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father.
        /// </summary>
        internal static string founder_dwarf {
            get {
                return ResourceManager.GetString("founder_dwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einior.
        /// </summary>
        internal static string founder_elf {
            get {
                return ResourceManager.GetString("founder_elf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief.
        /// </summary>
        internal static string founder_hobbit {
            get {
                return ResourceManager.GetString("founder_hobbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founder.
        /// </summary>
        internal static string founder_man {
            get {
                return ResourceManager.GetString("founder_man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founder.
        /// </summary>
        internal static string founder_mixed {
            get {
                return ResourceManager.GetString("founder_mixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian.
        /// </summary>
        internal static string guardian {
            get {
                return ResourceManager.GetString("guardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historian.
        /// </summary>
        internal static string historian {
            get {
                return ResourceManager.GetString("historian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobbit.
        /// </summary>
        internal static string hobbit {
            get {
                return ResourceManager.GetString("hobbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunter.
        /// </summary>
        internal static string hunter {
            get {
                return ResourceManager.GetString("hunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image you want to use is too small. It has to be 141*141 pixels minimum..
        /// </summary>
        internal static string imageTooSmall {
            get {
                return ResourceManager.GetString("imageTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string import {
            get {
                return ResourceManager.GetString("import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import a portrait
        ///of you char.
        /// </summary>
        internal static string importPortrait {
            get {
                return ResourceManager.GetString("importPortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeweller.
        /// </summary>
        internal static string jeweller {
            get {
                return ResourceManager.GetString("jeweller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinship Name:.
        /// </summary>
        internal static string kinName {
            get {
                return ResourceManager.GetString("kinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kin Membership Rank:.
        /// </summary>
        internal static string kinRank {
            get {
                return ResourceManager.GetString("kinRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give your
        ///kinship details.
        /// </summary>
        internal static string kinshipDetails {
            get {
                return ResourceManager.GetString("kinshipDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinship Type:.
        /// </summary>
        internal static string kinType {
            get {
                return ResourceManager.GetString("kinType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lord.
        /// </summary>
        internal static string leader_dwarf {
            get {
                return ResourceManager.GetString("leader_dwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tûr.
        /// </summary>
        internal static string leader_elf {
            get {
                return ResourceManager.GetString("leader_elf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader.
        /// </summary>
        internal static string leader_hobbit {
            get {
                return ResourceManager.GetString("leader_hobbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        internal static string leader_man {
            get {
                return ResourceManager.GetString("leader_man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader.
        /// </summary>
        internal static string leader_mixed {
            get {
                return ResourceManager.GetString("leader_mixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string level {
            get {
                return ResourceManager.GetString("level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lore-Master.
        /// </summary>
        internal static string loremaster {
            get {
                return ResourceManager.GetString("loremaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race of Man.
        /// </summary>
        internal static string man {
            get {
                return ResourceManager.GetString("man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string masterTier0 {
            get {
                return ResourceManager.GetString("masterTier0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Apprentice.
        /// </summary>
        internal static string masterTier1 {
            get {
                return ResourceManager.GetString("masterTier1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Journeyman.
        /// </summary>
        internal static string masterTier2 {
            get {
                return ResourceManager.GetString("masterTier2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Expert.
        /// </summary>
        internal static string masterTier3 {
            get {
                return ResourceManager.GetString("masterTier3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Artisan.
        /// </summary>
        internal static string masterTier4 {
            get {
                return ResourceManager.GetString("masterTier4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Master.
        /// </summary>
        internal static string masterTier5 {
            get {
                return ResourceManager.GetString("masterTier5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superior Master.
        /// </summary>
        internal static string masterTier6 {
            get {
                return ResourceManager.GetString("masterTier6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to master tier 7.
        /// </summary>
        internal static string masterTier7 {
            get {
                return ResourceManager.GetString("masterTier7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mastery Tier:.
        /// </summary>
        internal static string masteryTier {
            get {
                return ResourceManager.GetString("masteryTier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        internal static string member_dwarf {
            get {
                return ResourceManager.GetString("member_dwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        internal static string member_elf {
            get {
                return ResourceManager.GetString("member_elf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        internal static string member_hobbit {
            get {
                return ResourceManager.GetString("member_hobbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        internal static string member_man {
            get {
                return ResourceManager.GetString("member_man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        internal static string member_mixed {
            get {
                return ResourceManager.GetString("member_mixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metalsmith.
        /// </summary>
        internal static string metalsmith {
            get {
                return ResourceManager.GetString("metalsmith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minstrel.
        /// </summary>
        internal static string minstrel {
            get {
                return ResourceManager.GetString("minstrel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed.
        /// </summary>
        internal static string mixed {
            get {
                return ResourceManager.GetString("mixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Kinship.
        /// </summary>
        internal static string noKinship {
            get {
                return ResourceManager.GetString("noKinship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string noProfession {
            get {
                return ResourceManager.GetString("noProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of .
        /// </summary>
        internal static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of .
        /// </summary>
        internal static string of2 {
            get {
                return ResourceManager.GetString("of2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of 7.
        /// </summary>
        internal static string of7 {
            get {
                return ResourceManager.GetString("of7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seneschal.
        /// </summary>
        internal static string officer_dwarf {
            get {
                return ResourceManager.GetString("officer_dwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caun.
        /// </summary>
        internal static string officer_elf {
            get {
                return ResourceManager.GetString("officer_elf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voluntary Assistant Chief.
        /// </summary>
        internal static string officer_hobbit {
            get {
                return ResourceManager.GetString("officer_hobbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provost.
        /// </summary>
        internal static string officer_man {
            get {
                return ResourceManager.GetString("officer_man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officer.
        /// </summary>
        internal static string officer_mixed {
            get {
                return ResourceManager.GetString("officer_mixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professions:.
        /// </summary>
        internal static string professions {
            get {
                return ResourceManager.GetString("professions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prospector.
        /// </summary>
        internal static string prospector {
            get {
                return ResourceManager.GetString("prospector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PvMP.
        /// </summary>
        internal static string pvmp {
            get {
                return ResourceManager.GetString("pvmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PvMP Rank:.
        /// </summary>
        internal static string pvmpRank {
            get {
                return ResourceManager.GetString("pvmpRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        internal static string race {
            get {
                return ResourceManager.GetString("race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unranked.
        /// </summary>
        internal static string rank_0 {
            get {
                return ResourceManager.GetString("rank_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank 1 (Footman).
        /// </summary>
        internal static string rank_1 {
            get {
                return ResourceManager.GetString("rank_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank 10 (Lieutenant).
        /// </summary>
        internal static string rank_10 {
            get {
                return ResourceManager.GetString("rank_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank 11 (Commander).
        /// </summary>
        internal static string rank_11 {
            get {
                return ResourceManager.GetString("rank_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank 12 (Third Marshall).
        /// </summary>
        internal static string rank_12 {
            get {
                return ResourceManager.GetString("rank_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank 13 (Second Marshall).
        /// </summary>
        internal static string rank_13 {
            get {
                return ResourceManager.GetString("rank_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank 14 (First Marshall).
        /// </summary>
        internal static string rank_14 {
            get {
                return ResourceManager.GetString("rank_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank 15 (Captain-General).
        /// </summary>
        internal static string rank_15 {
            get {
                return ResourceManager.GetString("rank_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank 2 (Esquire).
        /// </summary>
        internal static string rank_2 {
            get {
                return ResourceManager.GetString("rank_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank 3 (Guardsman).
        /// </summary>
        internal static string rank_3 {
            get {
                return ResourceManager.GetString("rank_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank 4 (Man-at-Arms).
        /// </summary>
        internal static string rank_4 {
            get {
                return ResourceManager.GetString("rank_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank 5 (Sergeant of the Guard).
        /// </summary>
        internal static string rank_5 {
            get {
                return ResourceManager.GetString("rank_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank 6 (Sergeant-at-Arms).
        /// </summary>
        internal static string rank_6 {
            get {
                return ResourceManager.GetString("rank_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank 7 (Master Guardsman).
        /// </summary>
        internal static string rank_7 {
            get {
                return ResourceManager.GetString("rank_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank 8 (Master-at-Arms).
        /// </summary>
        internal static string rank_8 {
            get {
                return ResourceManager.GetString("rank_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank 9 (High Warden).
        /// </summary>
        internal static string rank_9 {
            get {
                return ResourceManager.GetString("rank_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to cancel?
        ///Doing so will discard all data you have entered..
        /// </summary>
        internal static string reallyCancel {
            get {
                return ResourceManager.GetString("reallyCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruit.
        /// </summary>
        internal static string recruit_dwarf {
            get {
                return ResourceManager.GetString("recruit_dwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruit.
        /// </summary>
        internal static string recruit_elf {
            get {
                return ResourceManager.GetString("recruit_elf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruit.
        /// </summary>
        internal static string recruit_hobbit {
            get {
                return ResourceManager.GetString("recruit_hobbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruit.
        /// </summary>
        internal static string recruit_man {
            get {
                return ResourceManager.GetString("recruit_man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruit.
        /// </summary>
        internal static string recruit_mixed {
            get {
                return ResourceManager.GetString("recruit_mixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rune-Keeper.
        /// </summary>
        internal static string runekeeper {
            get {
                return ResourceManager.GetString("runekeeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as File.
        /// </summary>
        internal static string save2file {
            get {
                return ResourceManager.GetString("save2file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string scale {
            get {
                return ResourceManager.GetString("scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scholar.
        /// </summary>
        internal static string scholar {
            get {
                return ResourceManager.GetString("scholar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your
        ///PvMP rank.
        /// </summary>
        internal static string selectPvmp {
            get {
                return ResourceManager.GetString("selectPvmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:.
        /// </summary>
        internal static string server {
            get {
                return ResourceManager.GetString("server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small preview, actual image is 4 times as large.
        /// </summary>
        internal static string smallPreview {
            get {
                return ResourceManager.GetString("smallPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stars:.
        /// </summary>
        internal static string stars {
            get {
                return ResourceManager.GetString("stars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  stars.
        /// </summary>
        internal static string stars2 {
            get {
                return ResourceManager.GetString("stars2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        internal static string step {
            get {
                return ResourceManager.GetString("step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature successfully created.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tailor.
        /// </summary>
        internal static string tailor {
            get {
                return ResourceManager.GetString("tailor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tier:.
        /// </summary>
        internal static string tier {
            get {
                return ResourceManager.GetString("tier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string tier0 {
            get {
                return ResourceManager.GetString("tier0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apprentice.
        /// </summary>
        internal static string tier1 {
            get {
                return ResourceManager.GetString("tier1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journeyman.
        /// </summary>
        internal static string tier2 {
            get {
                return ResourceManager.GetString("tier2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        internal static string tier3 {
            get {
                return ResourceManager.GetString("tier3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artisan.
        /// </summary>
        internal static string tier4 {
            get {
                return ResourceManager.GetString("tier4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        internal static string tier5 {
            get {
                return ResourceManager.GetString("tier5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superior.
        /// </summary>
        internal static string tier6 {
            get {
                return ResourceManager.GetString("tier6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tier 7.
        /// </summary>
        internal static string tier7 {
            get {
                return ResourceManager.GetString("tier7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tinker.
        /// </summary>
        internal static string tinker {
            get {
                return ResourceManager.GetString("tinker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use default image.
        /// </summary>
        internal static string useDefault {
            get {
                return ResourceManager.GetString("useDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your own characters&apos;s portrait.
        /// </summary>
        internal static string useImportedPortrait {
            get {
                return ResourceManager.GetString("useImportedPortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Ring Symbol.
        /// </summary>
        internal static string useRingSymbol {
            get {
                return ResourceManager.GetString("useRingSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocation:.
        /// </summary>
        internal static string vocation {
            get {
                return ResourceManager.GetString("vocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warden.
        /// </summary>
        internal static string warden {
            get {
                return ResourceManager.GetString("warden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weaponsmith.
        /// </summary>
        internal static string weaponsmith {
            get {
                return ResourceManager.GetString("weaponsmith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woodsman.
        /// </summary>
        internal static string woodsman {
            get {
                return ResourceManager.GetString("woodsman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woodworker.
        /// </summary>
        internal static string woodworker {
            get {
                return ResourceManager.GetString("woodworker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeoman.
        /// </summary>
        internal static string yeoman {
            get {
                return ResourceManager.GetString("yeoman", resourceCulture);
            }
        }
    }
}
